services:
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/voyo/linux_amd64_redis:7.4.1-alpine3.20
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: 10
    ports:
      - "6379:6379"
    volumes:
      - "/home/redis/conf:/usr/local/etc/redis"
    command: 
      - redis-server 
      - /usr/local/etc/redis/redis.conf
