services:
  redis:
    image: redis:7.0.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/redis/conf:/usr/local/etc/redis"
    command: 
      - redis-server 
      - /usr/local/etc/redis/redis.conf
